# Generated by Django 2.1 on 2018-08-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
