# Generated by Django 2.1 on 2018-08-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20180821_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': {('crm_table_obj_list', '可以查看kingadmin下的customer表')}},
        ),
    ]
